### ISSUE TITLE
ImportError: No module named cfscrape

### ISSUE THREAD

**Issue by WilliamAnthony** [Xonshiz/comic-dl#115]
I followed install instruction on my ubuntu linux 14.04. No error at all. After finished, I tried executing:

./__main__.py

there was an error:

Traceback (most recent call last):
  File "./__main__.py", line 4, in <module>
    from comic_dl import ComicDL
  File "/home/william/opt/comic_dl/comic_dl/comic_dl.py", line 9, in <module>
    import honcho
  File "/home/william/opt/comic_dl/comic_dl/honcho.py", line 9, in <module>
    from sites import foolSlide
  File "/home/william/opt/comic_dl/comic_dl/sites/foolSlide.py", line 4, in <module>
    import globalFunctions
  File "/home/william/opt/comic_dl/comic_dl/globalFunctions.py", line 4, in <module>
    import cfscrape
ImportError: No module named cfscrape

**Comment by Xonshiz** [comment]
You need to run `pip install - r requirements.txt`
The error shows that you don't have the cfscrape library installed.

**Comment by WilliamAnthony** [comment]
Done, thanks.
