### ISSUE TITLE
cloudfare scrape error

### ISSUE THREAD

**Issue by pnupy** [Xonshiz/comic-dl#118]
I've started encountering an issue where the script crashes because of an error in Cloudfare-scrape. It seems that it is a new issue, which has already been reported (Anorov/cloudflare-scrape#145) to the creators of that module although not yet fixed.

Console Output:
Traceback (most recent call last):
  File "comic_dl\__main__.py", line 10, in <module>
  File "comic_dl\comic_dl.py", line 234, in __init__
  File "comic_dl\honcho.py", line 100, in checker
  File "comic_dl\sites\readcomicOnlineto.py", line 28, in __init__
  File "comic_dl\sites\readcomicOnlineto.py", line 93, in full_series
  File "comic_dl\globalFunctions.py", line 31, in page_downloader
  File "requests\sessions.py", line 521, in get
  File "site-packages\cfscrape\__init__.py", line 48, in request
  File "site-packages\cfscrape\__init__.py", line 78, in solve_cf_challenge
  File "site-packages\cfscrape\__init__.py", line 108, in solve_challenge
ValueError: Error parsing Cloudflare IUAM Javascript challenge. Cloudflare may have changed their technique, or there may be a bug in the script.

Please read https://github.com/Anorov/cloudflare-scrape#updates, then file a bug report at https://github.com/Anorov/cloudflare-scrape/issues.
[23636] Failed to execute script __main__

**Comment by Xonshiz** [comment]
Yes, I'm aware of the issue. @Anorov has fixed it, I'll release an updated version later today.

**Comment by Xonshiz** [comment]
Check the [Latest Release](https://github.com/Xonshiz/comic-dl/releases/tag/2018.03.23.a).
