### ISSUE TITLE
ImportError: No module named clint.textui

### ISSUE THREAD

**Issue by hallwayorchard** [Xonshiz/comic-dl#122]
Hi Xonshiz,

While attempting to update to the latest script, I get the following error when trying to execute the final installation step:
`./__main__.py

Traceback (most recent call last):
  File "./__main__.py", line 4, in <module>
    from comic_dl import ComicDL
  File "/home/linus/Desktop/COMICDL/comic_dl/comic_dl.py", line 9, in <module>
    import honcho
  File "/home/linus/Desktop/COMICDL/comic_dl/honcho.py", line 9, in <module>
    from sites import foolSlide
  File "/home/linus/Desktop/COMICDL/comic_dl/sites/foolSlide.py", line 4, in <module>
    import globalFunctions
  File "/home/linus/Desktop/COMICDL/comic_dl/globalFunctions.py", line 7, in <module>
    from clint.textui import progress
ImportError: No module named clint.textui`

I've tried this a few times, all the way from scratch, always stuck at this one point.

Any help would be much appreciated!

**Comment by hallwayorchard** [comment]
UPDATE:
I finally got one step closer by installing _python_-clint

`sudo apt-get install python-clint`

I was greeted with another error for `img2pdf`

This required an install of `pip3` (a dependency) and `img2pdf`

`sudo apt-get install python3-pip`
`sudo pip3 install img2pdf`

This appeared to be successful, however I am still getting the following error

`./__main__.py`
Traceback (most recent call last):
 ` File "./__main__.py", line 4, in <module>`
    from comic_dl import ComicDL
  File "/home/linus/Desktop/COMICDL/comic_dl/comic_dl.py", line 9, in <module>
    import honcho
  File "/home/linus/Desktop/COMICDL/comic_dl/honcho.py", line 9, in <module>
    from sites import foolSlide
  File "/home/linus/Desktop/COMICDL/comic_dl/sites/foolSlide.py", line 4, in <module>
    import globalFunctions
  File "/home/linus/Desktop/COMICDL/comic_dl/globalFunctions.py", line 14, in <module>
    import img2pdf
ImportError: No module named img2pdf

**Comment by hallwayorchard** [comment]
UPDATE:
Out of options, I tried to get this up and running on a Windows machine... which ended up giving me a clue.  The error in windows mentioned a possible update to the cloudfare-scrape.

Armed with this, I updated the cloudfare as follows:

`sudo pip install cfscrape -U`

Ended up with another error due to nodejs... updated nodejs and installed the legacy version (which ended up being required due to some reason or another) as follows:

`sudo apt-get install nodejs`
`sudo apt-get install nodejs-legacy`

After this I am happily downloading again.

Wanted to update this thread in case anyone else ran into the issue.

Cheers
