### ISSUE TITLE
[27492] Failed to execute script __main__

### ISSUE THREAD

**Issue by StrangeDOS** [Xonshiz/comic-dl#143]
Running the Windows binary using the following....

comic_dl -i http://readcomiconline.to/Comic/Aspen-Universe-Decimation -v

The first chapter started to download and then I got the following...

Traceback (most recent call last):
  File "comic_dl\__main__.py", line 10, in <module>
  File "comic_dl\comic_dl.py", line 226, in __init__
  File "comic_dl\honcho.py", line 100, in checker
  File "comic_dl\sites\readcomicOnlineto.py", line 28, in __init__
  File "comic_dl\sites\readcomicOnlineto.py", line 141, in full_series
IndexError: list index out of range
[27492] Failed to execute script __main__

NOTE:  This has 5 chapters and for some reason it started at number 4.  

Attaching verbose log.
[Error_Log.log](https://github.com/Xonshiz/comic-dl/files/2099740/Error_Log.log)

**Comment by StrangeDOS** [comment]
NOTE:  I fell back to using Script Version : 2018.04.29.  The problem went away.

This seems to be an issue with Script Version : 2018.05.21.

Hope that helps.
