### ISSUE TITLE
Naver Comics (broken) & Line Webtoons (unsupported)

### ISSUE THREAD

**Issue by jamesdeluk** [Xonshiz/comic-dl#166]
**Naver** doesn't download any pages:
Directory Path : /Users/xxx/Downloads/183559/389
     =====================================================================
                              Manga Name : 183559
                              Chapter Number - 389
                                Total Pages - 0
     =====================================================================
Total Time Taken To Complete : 0.521471977234

**Webtoons** isn't supported.

**Comment by Xonshiz** [comment]
please run the program again with `--verbose` flag and post the log file here.

**Comment by jamesdeluk** [comment]
python3 __main__.py -i https://comic.naver.com/webtoon/detail.nhn\?titleId\=183559\&no\=1 -v

```
***Starting the script in Verbose Mode***

Directory Path : /~/183559/1


     =====================================================================
                              Manga Name : 183559
                               Chapter Number - 1
                                Total Pages - 0
     =====================================================================

Total Time Taken To Complete : 0.3270261287689209
```

And for a title, with keyboard interrupt (dunno if that helps)

```
python3 __main__.py -i https://comic.naver.com/webtoon/list.nhn\?titleId\=183559 -v

***Starting the script in Verbose Mode***

Directory Path : /~/183559/399


     =====================================================================
                              Manga Name : 183559
                              Chapter Number - 399
                                Total Pages - 0
     =====================================================================

Directory Path : /~/183559/398


     =====================================================================
                              Manga Name : 183559
                              Chapter Number - 398
                                Total Pages - 0
     =====================================================================

Directory Path : /~/183559/397


     =====================================================================
                              Manga Name : 183559
                              Chapter Number - 397
                                Total Pages - 0
     =====================================================================

Directory Path : /~/183559/396


     =====================================================================
                              Manga Name : 183559
                              Chapter Number - 396
                                Total Pages - 0
     =====================================================================

Directory Path : /~/183559/395


     =====================================================================
                              Manga Name : 183559
                              Chapter Number - 395
                                Total Pages - 0
     =====================================================================

^CTraceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/urllib3/connectionpool.py", line 377, in _make_request
    httplib_response = conn.getresponse(buffering=True)
TypeError: getresponse() got an unexpected keyword argument 'buffering'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "__main__.py", line 10, in <module>
    ComicDL(sys.argv[1:])
  File "/~/comic_dl.py", line 226, in __init__
    comic_language=args.manga_language[0])
  File "/~/honcho.py", line 107, in checker
    delete_files=kwargs.get("delete_files"))
  File "/~/sites/comicNaver.py", line 21, in __init__
    conversion=conversion, delete_files=delete_files)
  File "/~/sites/comicNaver.py", line 108, in full_series
    conversion=conversion, delete_files=delete_files)
  File "/~/sites/comicNaver.py", line 36, in single_chapter
    source, cookies = globalFunctions.GlobalFunctions().page_downloader(manga_url=comic_url)
  File "/~/globalFunctions.py", line 32, in page_downloader
    connection = sess.get(manga_url, headers=headers, cookies=kwargs.get("cookies"))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/requests/sessions.py", line 525, in get
    return self.request('GET', url, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/cfscrape/__init__.py", line 64, in request
    resp = super(CloudflareScraper, self).request(method, url, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/requests/sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/requests/sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/requests/adapters.py", line 445, in send
    timeout=timeout
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1321, in getresponse
    response.begin()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 296, in begin
    version, status, reason = self._read_status()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 257, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
KeyboardInterrupt
```

**Comment by jamesdeluk** [comment]
I found this error log:

```
DEBUG: Arguments Provided : Namespace(auto=False, chapter_id=None, config=False, convert=None, download_directory=['/~/Comics'], force_download=False, input=['https://comic.naver.com/webtoon/detail.nhn?titleId=183559&no=1'], keep=['True'], manga_language='0', page_id=None, password=['None'], quality='True', range='All', search=None, skip_cache='0', sorting=None, username=['None'], verbose=True, version=False)
DEBUG: Operating System : Darwin - 17.7.0 - Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64
DEBUG: Python Version : 2.7.10 (64bit)
DEBUG: Script Version : 2018.07.27
DEBUG: Comic Url : https://comic.naver.com/webtoon/detail.nhn?titleId=183559&no=1
DEBUG: Selected Domain : comic.naver.com
DEBUG: Starting new HTTPS connection (1): comic.naver.com:443
DEBUG: https://comic.naver.com:443 "GET /webtoon/detail.nhn?titleId=183559&no=1 HTTP/1.1" 200 20514
DEBUG: Image List : []
```

**Comment by jamesdeluk** [comment]
Fixed! Thanks darodi!!
