### ISSUE TITLE
List index out of range

### ISSUE THREAD

**Issue by DeadmanGER** [Xonshiz/comic-dl#207]
PS D:\tlutz\comic-dl\comic-dl> .\comic_dl.exe -i https://readcomiconline.to/Comic/The-Punisher-2016 --quality high --convert pdf --verbose
Fooling CloudFlare...Please Wait...

     =====================================================================
                         Manga Name : The Punisher 2016
                          Chapter Number - Issue - 226
                                Total Pages - 0
     =====================================================================

Couldn't write the pdf file...
list index out of range
Deleted the files...
Fooling CloudFlare...Please Wait...
Traceback (most recent call last):
  File "comic_dl\__main__.py", line 10, in <module>
  File "comic_dl\comic_dl.py", line 226, in __init__
  File "comic_dl\honcho.py", line 101, in checker
  File "comic_dl\sites\readcomicOnlineto.py", line 28, in __init__
  File "comic_dl\sites\readcomicOnlineto.py", line 139, in full_series
  File "comic_dl\sites\readcomicOnlineto.py", line 43, in single_chapter
  File "comic_dl\globalFunctions.py", line 32, in page_downloader
  File "site-packages\requests\sessions.py", line 525, in get
  File "site-packages\cfscrape\__init__.py", line 68, in request
  File "site-packages\cfscrape\__init__.py", line 73, in solve_cf_challenge
KeyboardInterrupt
[17328] Failed to execute script __main__

PS D:\tlutz\comic-dl\comic-dl> .\comic_dl.exe --version
Current Version : 2018.09.24

Geting this everytime I try to download:  https://readcomiconline.to/Comic/The-Punisher-2016

Thanks for your help and your hard work

**Comment by Xonshiz** [comment]
Working just fine on my end. Please try with the latest release.

![image](https://user-images.githubusercontent.com/13240567/51781212-a960ef00-213b-11e9-910a-a509ff8d9548.png)
