### ISSUE TITLE
TypeError: can only concatenate list (not "map") to list

### ISSUE THREAD

**Issue by MayRedBeWithYou** [Xonshiz/comic-dl#208]
I tried using this command:
> python __main__.py -i "https://mangarock.com/manga/mrs-serie-256580/chapter/mrs-chapter-
256581" --convert pdf

Files are downloaded in .mri format, but right after that this happens:
```
Decrypting Files...
Traceback (most recent call last):
  File "__main__.py", line 10, in <module>
    ComicDL(sys.argv[1:])
  File "F:\comic-dl-master\comic_dl\comic_dl.py", line 238, in __init__
    comic_language=args.manga_language[0], print_index=print_index)
  File "F:\comic-dl-master\comic_dl\honcho.py", line 183, in checker
    print_index=print_index)
  File "F:\comic-dl-master\comic_dl\sites\mangaRock.py", line 30, in __init__
    download_directory=download_directory, conversion=conversion, keep_files=keep_files)
  File "F:\comic-dl-master\comic_dl\sites\mangaRock.py", line 95, in single_chapter
    self.file_decryption(path_to_files=directory_path) # Calling the method that does the magic!
  File "F:\comic-dl-master\comic_dl\sites\mangaRock.py", line 64, in file_decryption
    open(str(mri_file).replace(".mri", ".jpg"), 'wb').write(''.join(map(chr, header + data)))
TypeError: can only concatenate list (not "map") to list
```
Here is the [Error_Log.log](https://github.com/Xonshiz/comic-dl/files/2799036/Error_Log.log)

**Comment by Dorsug** [comment]
It's because of the changement of behavior of map between python 2 and 3. To correct it you need to change the line 62 of comic-dl-master\comic_dl\sites\mangaRock.py to `data = list(map(lambda x: ord(x) ^ 101, data))`.
I'm hesitant to do a pull request just for one line change.

**Comment by Dorsug** [comment]
The same problem occur two lines after with `join(map(chr, header + data)` which need to be `join(list(map(chr, header + data))`. But then another error occur
```
Traceback (most recent call last):
  File "/Users/dorsug/Programms/comic-dl/comic_dl/sites/mangaRock.py", line 63, in file_decryption
    data = list(map(lambda x: ord(x) ^ 101, data))
  File "/Users/dorsug/Programms/comic-dl/comic_dl/sites/mangaRock.py", line 63, in <lambda>
    data = list(map(lambda x: ord(x) ^ 101, data))
 TypeError: ord() expected string of length 1, but int found
```
Also due to python 2 -> 3 and the change of how binary is handled.
I don't understand the decryption enough to be able to patch it.

**Comment by Dorsug** [comment]
Pushed a pull request to fix but it creates webp files with a .jpg extension. It's weird but the same as before and pose no problem when converting to pdf or cbz.
