### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by UMLAUTaxl** [Xonshiz/comic-dl#220]
Hi, I tried this with several manga sites and nothing worked. So either I'm doing something wrong or this is completely broken.

```
$ ./__main__.py -v -i https://fanfox.net/manga/dagashi_kashi/v08/c141/1.html

***Starting the script in Verbose Mode***

Traceback (most recent call last):
  File "./__main__.py", line 10, in <module>
    ComicDL(sys.argv[1:])
  File "/media/Disk1/comic-dl/comic_dl/comic_dl.py", line 237, in __init__
    comic_language=args.manga_language[0], print_index=print_index)
  File "/media/Disk1/comic-dl/comic_dl/honcho.py", line 130, in checker
    print_index=print_index)
  File "/media/Disk1/comic-dl/comic_dl/sites/mangaFox.py", line 29, in __init__
    keep_files=keep_files)
  File "/media/Disk1/comic-dl/comic_dl/sites/mangaFox.py", line 41, in single_chapter
    current_chapter_volume = str(re.search(r"current_chapter=\"(.*?)\";", str(source)).group(1))
AttributeError: 'NoneType' object has no attribute 'group'
```

Error_Log.log: https://gist.github.com/UMLAUTaxl/1054634cda967a96c290e71c9a8e12e2

I guess I should reference #004 but it's closed.
Thanks

**Comment by Xonshiz** [comment]
Hey, could you download latest binary and try again and update here?

**Comment by Xonshiz** [comment]
Closing, as added with [latest commit](https://github.com/Xonshiz/comic-dl/commit/d236e7537768310416a1663dc53163dcc386ceac).
