### ISSUE TITLE
Script "can't connect to website" - Response 403

### ISSUE THREAD

**Issue by Guillaume-Garrigos** [Xonshiz/comic-dl#273]
Hi,

I just installed the script and it is not working for me. Both the windows script and the python one return the same error: after running `python __main__.py -find "One Piece"` (from the appropriate folder) or `comic_dl.exe -find "One Piece"`, I obtain the following message error:
```
Downloading The Latest Data Set...
Whoops! Seems like I can't connect to website.
It's showing : <Response [403]>
```
With the `--verbose` argument, it produces the following logfile:
```
DEBUG: Arguments Provided : Namespace(auto=False, chapter_id=None, comic=False, comic_info=None, config=False, convert=None, download_directory=['C:\\Users\\XXXX\\Desktop'], force_download=False, input=None, keep=['True'], manga_language='0', page_id=None, password=['None'], print_index=False, quality='True', range='All', search=['One Piece'], search_comic=None, skip_cache='0', sorting=None, update=None, username=['None'], verbose=True, version=False)
DEBUG: Operating System : Windows - 10 - 10.0.18362
DEBUG: Python Version : 3.7.6 (64bit)
DEBUG: Script Version : 2019.05.26
DEBUG: Starting new HTTP connection (1): www.mangaeden.com:80
DEBUG: http://www.mangaeden.com:80 "GET /api/list/0/ HTTP/1.1" 403 None
```

At that point I don't know what to do? 
I precise that I installed all the dependencies as required (Node.js, Phantom.js, python) and added them to the PATH (I can access each of them from anywhere with the terminal).

Cheers
Guillaume

**Comment by njscorpion** [comment]
Facing the same issue

**Comment by Xonshiz** [comment]
Could you please try this again and update me? I'll take a look if the issue is still there.

**Comment by Guillaume-Garrigos** [comment]
So it seems that there is a progress. I do not get an error, but : 
```
Downloading The Latest Data Set...
Searching for One Piece in the Database...
Total Time Taken To Search : 0.336000204086
API Provided By Manga Eden : http://www.mangaeden.com/
```

Is it what I am supposed to get? The main documentation says that the result should look like this :
```
Manga Name  --> Manga ID
------------------------
One Piece: Wanted! --> 4e70ea60c092255ef7006726
One Piece (Databook) --> 5218b0ef45b9ef8b83731b00
One Piece x Toriko --> 4e70ea75c092255ef7006ee2
One Piece dj - Boukyaku Countdown --> 55a19e2b719a1609004ad1f3
One Piece --> 4e70ea10c092255ef7004aa2
One Piece Party --> 566d9611719a1697dd8cf79a
One Piece dj - Tears Will Surely Turn into Strength --> 55a19e31719a1609004ad1f7
One Piece dj - Lotus Maker --> 55a19e2e719a1609004ad1f5
One Piece dj - Three Days of Extreme Extravagance --> 55a19e34719a1609004ad1f9
```

**Comment by Guillaume-Garrigos** [comment]
I don't know if it is related but I did not updated comic-dl before trying again, in the above answer. Maybe that was implicit in your demand?

After updating comic-dl from the [repo](https://github.com/Xonshiz/comic-dl/archive/master.zip), I'm getting a bunch of errors. It seems that a lot of paths have been turned into relative paths and the system is not liking it : 

```
Traceback (most recent call last):
  File "__main__.py", line 10, in <module>
    from comic_dl.__version__ import __version__
  File "D:\Documents\config_xps\comic-dl\comic-dl-master\comic_dl\comic_dl.py", line 6, in <module>
    from .__version__ import __version__
ImportError: attempted relative import with no known parent package
```

**Comment by Xonshiz** [comment]
Ohhh yeah the relative path errors. I fixed it with a work-around for building the binaries/distributables. But, looks like the code will still have those issues. I'll park the import issues for now with code.
But as for the original issue, seems like something changed in mangaeden api.
Thanks for checking this one. I'll see whenever I get some time to look into this.

**Comment by jackkerouac** [comment]
I have the same issue, but I get <Reponse [522]>. Log File:

```
DEBUG: Arguments Provided : Namespace(version=False, sorting=None, auto=False, config=False, download_directory=['D:\\Downloads - Complete'], range='All', convert=None, keep=['True'], quality='True', input=None, cookie=None, comic=False, search_comic=None, comic_info=None, update=None, print_index=False, search=['Monsters'], manga_language='0', skip_cache='0', chapter_id=None, page_id=None, force_download=False, password=['None'], username=['None'], verbose=True)
DEBUG: Operating System : Windows - 10 - 10.0.22000
DEBUG: Python Version : 3.9.12 (64bit)
DEBUG: Script Version : 2022.04.23
DEBUG: Starting new HTTP connection (1): www.mangaeden.com:80
DEBUG: http://www.mangaeden.com:80 "GET /api/list/0/ HTTP/1.1" 301 None
DEBUG: Starting new HTTPS connection (1): www.mangaeden.com:443
DEBUG: https://www.mangaeden.com:443 "GET /api/list/0/ HTTP/1.1" 522 None
```

**Comment by darodi** [comment]
Seems dead 

Website Name: Mangaeden
URL Checked: mangaeden.com
Response Time: 0.95 ms.
Down For: more than a week

https://www.isitdownrightnow.com/mangaeden.com.html

![image](https://user-images.githubusercontent.com/4682830/169148294-2ea0d61f-881f-41da-9a07-fd7ffd2f8ca5.png)

**Comment by Xonshiz** [comment]
Yeah, time to remove manga Eden and the search feature for now. I think I was looking into an alternative and I might've found one. I'll take a look at that next week if I get some time. Will keep this open till I remove the search or fix it.

**Comment by darodi** [comment]
@Xonshiz 

6 months later, the site is still down. 
Time to clean it up?

**Comment by Xonshiz** [comment]
I want to, but I don't want to.. :(
I'll give it another try around this month, let's see and decide the fate of this one.

**Comment by tabletseeker** [comment]
Try out the only working downloader for readcomicsonline.li in 2024: https://github.com/tabletseeker/readcomic_dl
