### ISSUE TITLE
Cannot install this anymore

### ISSUE THREAD

**Issue by Aemilian666** [Xonshiz/comic-dl#292]
On a new PC, and cannot install it anymore. 
I literally followed everything in the tutorial video, installed pip, etc.

However, when I open Command Prompt from the Folder, and run "Comic_dl.exe', I get this issue

Traceback (most recent call last):
  File "__main__.py", line 4, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 540, in exec_module
  File "__init__.py", line 8, in <module>
ImportError: cannot import name 'ComicDL' from partially initialized module 'comic_dl' (most likely due to a circular import) (C:\Users\mayfi\AppData\Local\Temp\_MEI79522\comic_dl\__init__.pyc)
[22552] Failed to execute script __main__

any advice? Thanks!

**Comment by Aemilian666** [comment]
Oh, and double-clicking the comic_dl.exe just crashes it.
