### ISSUE TITLE
Pip install is broken

### ISSUE THREAD

**Issue by Nekmo** [Xonshiz/comic-dl#3]
```
[nekmo@homura ~]$ sudo pip install comic-dl
The directory '/home/nekmo/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/nekmo/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting comic-dl
  Downloading comic-dl-2016.11.26.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-sy5cfysi/comic-dl/setup.py", line 17, in <module>
        readme = open('ReadMe.md').read()
    FileNotFoundError: [Errno 2] No such file or directory: 'ReadMe.md'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-sy5cfysi/comic-dl/
```

**Comment by Xonshiz** [comment]
Thanks for bringing this issue up. Forgot to update the pypi for this. I'll update it by this weekend :)

**Comment by Xonshiz** [comment]
@Nekmo it should be fixed now. Please try and let me know if the issue persists. As you can see, this project isn't properly maintained in terms of codes and hence, there might be problems while fetching this from PyPI. So, I recommend cloning/forking this repo or downloading the binary exe.

**Comment by bronikowski** [comment]
```λ /tmp/comic-dl/ master* sudo pip3 install comic_dl
Collecting comic_dl
  Using cached https://files.pythonhosted.org/packages/8e/b9/75eccfae9276fdaefedbe556fd6e6fd7bccc64fd7e12a8ff5081ddc57c63/comic_dl-2018.01.10.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-nv80oj7n/comic-dl/setup.py", line 3, in <module>
        readme = open('ReadMe.md').read()
    FileNotFoundError: [Errno 2] No such file or directory: 'ReadMe.md'
```

I think the problem returned?

```
λ /tmp/test/ wget -q https://files.pythonhosted.org/packages/8e/b9/75eccfae9276fdaefedbe556fd6e6fd7bccc64fd7e12a8ff5081ddc57c63/comic_dl-2018.01.10.zip -O comic.zip
λ /tmp/test/ unzip comic.zip 
Archive:  comic.zip
  inflating: comic_dl-2018.01.10/PKG-INFO
  inflating: comic_dl-2018.01.10/setup.cfg
  inflating: comic_dl-2018.01.10/setup.py
[…]
````

**Comment by DuendeInexistente** [comment]
Having the same issue here.
