### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by himansh-u** [Xonshiz/comic-dl#318]
_I followed all the instructions, downloaded packages and installed node.js. Is there some error in the way I added link?_

E:\New folder>comic_dl.exe -i https://readcomiconline.li/Comic/Raw/Issue-8?id=161579
Fooling CloudFlare...Please Wait...
Whoops! Seems like I can't connect to website.
It's showing : <Response [403]>
Run this script with the --verbose argument and report the issue along with log file on Github.
Traceback (most recent call last):
  File "cli.py", line 5, in <module>
  File "comic_dl\__main__.py", line 21, in main
  File "comic_dl\comic_dl.py", line 284, in __init__
  File "comic_dl\honcho.py", line 102, in checker
  File "comic_dl\sites\readcomicOnlineli.py", line 53, in __init__
  File "comic_dl\sites\readcomicOnlineli.py", line 83, in single_chapter
  File "comic_dl\globalFunctions.py", line 60, in page_downloader
Warning: can't connect to website https://readcomiconline.li/Comic/Raw/Issue-8?id=161579#1
[6880] Failed to execute script 'cli' due to unhandled exception!

**Comment by Xonshiz** [comment]
Duplicate for #299
