### ISSUE TITLE
403 forbitten

### ISSUE THREAD

**Issue by blercstudio** [Xonshiz/comic-dl#319]
comic-dl-master\comic-dl-master> .\comic_dl.exe -i "https://readcomiconline.li/Comic/Star-Wars-Darth-Vader-and-the-Lost-Command-2011/Issue-1?id=74747#1"
Fooling CloudFlare...Please Wait...
Whoops! Seems like I can't connect to website.
It's showing : <Response [403]>
Run this script with the --verbose argument and report the issue along with log file on Github.
Traceback (most recent call last):
  File "cli.py", line 5, in <module>
    main()
  File "comic_dl\__main__.py", line 21, in main
    ComicDL(sys.argv[1:])
  File "comic_dl\comic_dl.py", line 284, in __init__
    honcho.Honcho().checker(comic_url=user_input, current_directory=os.getcwd(),
  File "comic_dl\honcho.py", line 102, in checker
    readcomicOnlineli.ReadComicOnlineLi(manga_url=comic_url, logger=logging,
  File "comic_dl\sites\readcomicOnlineli.py", line 53, in __init__
    self.single_chapter(manga_url, self.comic_name, download_directory, conversion=conversion,
  File "comic_dl\sites\readcomicOnlineli.py", line 83, in single_chapter
    source, cookies = globalFunctions.GlobalFunctions().page_downloader(manga_url=comic_url, scrapper_delay=10, append_headers=self.appended_headers)
  File "comic_dl\globalFunctions.py", line 60, in page_downloader
    raise Warning("can't connect to website %s" % manga_url)
Warning: can't connect to website https://readcomiconline.li/Comic/Star-Wars-Darth-Vader-and-the-Lost-Command-2011/Issue-1?id=74747#1
[936] Failed to execute script 'cli' due to unhandled exception!
PS D:\[SOFTWARE]\comic-dl-master\comic-dl-master>

Too many errors, am i doing something wrong ? I probably am, right?

**Comment by Xonshiz** [comment]
All RCO issues will be linked to #299 and closed.
