### ISSUE TITLE
Kissmanga.py gives error

### ISSUE THREAD

**Issue by vomov** [Xonshiz/comic-dl#4]
When trying to download Berserk from Kissmanga (don't like the fact that I have to scroll, so downloading is preferable), I get the following after a couple of successful chapters:

```
Traceback (most recent call last):
  File "comic_dl\sites\kissmanga.py", line 85, in single_chapter
AttributeError: 'NoneType' object has no attribute 'group'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "comic_dl\comic_dl.py", line 80, in <module>
  File "comic_dl\comic_dl.py", line 76, in main
  File "comic_dl\honcho.py", line 53, in url_checker
  File "comic_dl\sites\kissmanga.py", line 155, in kissmanga_Url_Check
  File "comic_dl\sites\kissmanga.py", line 127, in whole_series
  File "comic_dl\sites\kissmanga.py", line 89, in single_chapter
AttributeError: 'NoneType' object has no attribute 'group'
Failed to execute script comic_dl
```

**Comment by Xonshiz** [comment]
@vomov Please read the `[ReadMe](https://github.com/Xonshiz/comic-dl#reporting-issues)` to see how to post a bug/issue. Please run the script with the `--verbose` flag and upload that output on gist and share that gist's result.

**Comment by Xonshiz** [comment]
Closing this one. Please add the Output of the verbose log and Re-Open this.

**Comment by vomov** [comment]
Apologies for the late response, here's the logfile.[Error Log.txt](https://github.com/Xonshiz/comic-dl/files/753817/Error.Log.txt)
