### ISSUE TITLE
ImportError: No module named cfscrape

### ISSUE THREAD

**Issue by temporaryaccount123** [Xonshiz/comic-dl#49]
I followed the tutorial but I end up with this after running ./__main__.py:

root@debian:/home/user/bin/comic-dl-master/comic_dl# ./__main__.py 
Traceback (most recent call last):
  File "./__main__.py", line 4, in <module>
    from comic_dl import ComicDL
  File "/home/user/bin/comic-dl-master/comic_dl/comic_dl.py", line 9, in <module>
    import honcho
  File "/home/user/bin/comic-dl-master/comic_dl/honcho.py", line 9, in <module>
    from sites import foolSlide
  File "/home/user/bin/comic-dl-master/comic_dl/sites/foolSlide.py", line 4, in <module>
    import globalFunctions
  File "/home/user/bin/comic-dl-master/comic_dl/globalFunctions.py", line 4, in <module>
    import cfscrape
ImportError: No module named cfscrape

Some additional info:
uname -a 
Linux debian 3.16.0-4-686-pae #1 SMP Debian 3.16.43-2+deb8u5 (2017-09-19) i686 GNU/Linux

python --version
Python 2.7.9

no errors were reported while installing dependencies.

**Comment by Xonshiz** [comment]
The error says "No module named cfscrape". You need "cfscrape" as well. Get "Cfscrape" python library as well by running `pip install cfscrape` and you'll need nodeJS as well.
