### ISSUE TITLE
Range Issue on readcomiconline.to

### ISSUE THREAD

**Issue by ducle2502** [Xonshiz/comic-dl#67]
Hello, I have been having this problem while trying to use the range option:

`_D:\Ebooks>comic_dl.exe -i http://readcomiconline.to/Comic/Lazarus-2013 --range 1-5

Traceback (most recent call last):

  File "comic_dl\__main__.py", line 9, in <module>

  File "comic_dl\comic_dl.py", line 74, in __init__

  File "comic_dl\honcho.py", line 52, in checker

  File "comic_dl\sites\readcomicOnlineto.py", line 29, in __init__

  File "comic_dl\sites\readcomicOnlineto.py", line 107, in full_series

AttributeError: 'str' object has no attribute 'isdecimal'

[8616] Failed to execute script __main__`_

_`D:\Ebooks>comic_dl.exe -i http://readcomiconline.to/Comic/Lazarus-2013 --range 5-a

Traceback (most recent call last):

  File "comic_dl\__main__.py", line 9, in <module>

  File "comic_dl\comic_dl.py", line 74, in __init__

  File "comic_dl\honcho.py", line 52, in checker

  File "comic_dl\sites\readcomicOnlineto.py", line 29, in __init__

  File "comic_dl\sites\readcomicOnlineto.py", line 107, in full_series

AttributeError: 'str' object has no attribute 'isdecimal'

[3044] Failed to execute script __main__`_

These are two instances when I am using the newest windows binary release. Hope you could look into this. Thank you very much.

**Comment by Xonshiz** [comment]
Please run "comic_dl.exe --version" and make sure that it says "2017.12.27". I just checked on my end and it's working. The older version had the issue that you just pointed out. I've released an updated version that fixes this issue. Please grab that one.
