### ISSUE TITLE
ImportError: No module named cfscrape

### ISSUE THREAD

**Issue by apollocreed** [Xonshiz/comic-dl#94]
Hi,
Thanks for the project it's wonderfull.
I cannot launch the __main__.py on linux. 
I'm pretty confident that I've installed all the dependencies. 
I've cloned the git directly to my machine.
This is what I've got :

```
Traceback (most recent call last):
  File "./__main__.py", line 4, in <module>
    from comic_dl import ComicDL
  File "/home/apollocreed/tmp/comic-dl-master/comic_dl/comic_dl.py", line 9, in <module>
    import honcho
  File "/home/apollocreed/tmp/comic-dl-master/comic_dl/honcho.py", line 9, in <module>
    from sites import foolSlide
  File "/home/apollocreed/tmp/comic-dl-master/comic_dl/sites/foolSlide.py", line 4, in <module>
    import globalFunctions
  File "/home/apollocreed/tmp/comic-dl-master/comic_dl/globalFunctions.py", line 4, in <module>
    import cfscrape
ImportError: No module named cfscrape
```
Cheers

**Comment by Xonshiz** [comment]
Hey, you haven't installed the dependencies. The error states that you don't have "cfscrape" library installed in your system. It's a python's package. Please run "python pip install cfscrape" and make sure it installs without any error.
